// Audio lesson step test (touch, iPhone size). BROWSER=webkit|chromium URL=... SHOT=prefix
const pw=require('playwright-core');
const URL=process.env.URL||'http://localhost:8766/';const BR=process.env.BROWSER||'webkit';const SHOT=process.env.SHOT;
const R=[];const ok=(n,c,i='')=>{R.push(c);console.log(c?'PASS':'FAIL',n,i);};
const LINK='https://example.com/lesson';
(async()=>{
 const b=BR==='webkit'?await pw.webkit.launch():await pw.chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
 const ctx=await b.newContext({viewport:{width:375,height:667},deviceScaleFactor:2,hasTouch:true,timezoneId:'America/New_York',serviceWorkers:'block',...(BR==='chromium'?{isMobile:true}:{})});
 await ctx.addInitScript(()=>{window.__opened=[];window.open=(u)=>{window.__opened.push(u);return {};};if(localStorage.getItem('seeded'))return;localStorage.setItem('seeded',1);const now=Date.now(),cards={};for(let i=0;i<300;i++)cards[i]={box:3,due:now+864e5,ok:3,bad:0};localStorage.setItem('n5VocabQuest.v1',JSON.stringify({cards,xp:100,streak:2,levels:['n5']}));});
 const p=await ctx.newPage();p.setDefaultTimeout(10000);const errs=[];p.on('pageerror',e=>errs.push(''+e));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))errs.push(m.text())});
 p.on('dialog',d=>d.accept());
 await p.goto(URL+'?t='+Date.now());await p.waitForTimeout(900);
 const ev=(f,a)=>p.evaluate(f,a);const tap=async s=>{await p.tap(s);await p.waitForTimeout(250);};
 const sec=()=>ev(()=>{const T=__N5.TS(),d=__N5.todayStr();return (T.days[d]||{sec:0}).sec});
 const noOvf=()=>ev(()=>document.documentElement.scrollWidth<=innerWidth);
 await p.waitForSelector('#alCard');
 ok('Home shows audio lesson step, Lesson 1/30',/Lesson 1/.test(await p.textContent('#alCard'))&&/1\/30/.test(await p.textContent('#alCard')));
 ok('no link by default',await ev(()=>__N5.AL().url===''));
 ok('home fits 375px with the card',await noOvf());
 await tap('#alOpen');ok('no link → prompt to add one',await ev(()=>/Add your lesson link/.test(document.querySelector('.modal').textContent)));
 ok('nothing opened without a link',await ev(()=>window.__opened.length===0));
 await tap('#alGoSet');await p.waitForSelector('#alUrl');ok('prompt opens Settings at Audio lesson',await ev(()=>!!document.querySelector('#alSection')));
 await p.fill('#alUrl','javascript:alert(1)');await ev(()=>document.querySelector('#alUrl').dispatchEvent(new Event('change')));
 ok('javascript: link rejected',await ev(()=>__N5.AL().url===''));
 await p.fill('#alUrl',LINK);await ev(()=>document.querySelector('#alUrl').dispatchEvent(new Event('change')));
 ok('link saved to this device only (localStorage)',await ev(u=>JSON.parse(localStorage.getItem('jlptVocabQuest.audioLesson.v1')).url===u,LINK));
 ok('link not in main progress blob',await ev(u=>!localStorage.getItem('n5VocabQuest.v1').includes(u),LINK));
 const setNum=async(s,v)=>{await p.fill(s,''+v);await ev(s=>document.querySelector(s).dispatchEvent(new Event('change')),s);};
 await setNum('#alTotal',40);await setNum('#alCur',3);await setNum('#alMin',25);
 ok('lesson settings saved',await ev(()=>{const A=__N5.AL();return A.total===40&&A.cur===3&&A.min===25}));
 ok('settings fits 375px',await noOvf());
 await tap('#tabHome');ok('Next: Lesson 3',/Next: Lesson 3/.test(await p.textContent('#alCard')));
 const s0=await sec();await tap('#alOpen');
 ok('tapping opens the saved link',await ev(u=>window.__opened[0]===u,LINK));
 await p.waitForSelector('#alDone');ok('after returning shows Mark lesson done',true);
 if(SHOT)await p.screenshot({path:SHOT+'al-mark.png'});
 await tap('#alDone');const s1=await sec();
 ok('mark done adds 25 min to today',s1-s0===1500,`${s0}->${s1}`);
 ok('lesson advances to 4',await ev(()=>__N5.AL().cur===4));
 ok('shows complete for today',/done/.test(await p.textContent('#alCard'))&&!!(await p.$('#alUndo')));
 ok('daily goal reached by the lesson',await ev(()=>__N5.goalMet()));
 ok('time pill updated',/^25\//.test(await p.textContent('#sTime')),await p.textContent('#sTime'));
 await ev(()=>__N5.alMarkDone());ok('only once per day',await sec()===s1&&await ev(()=>__N5.AL().cur===4));
 await tap('#alUndo');ok('undo removes minutes and lesson',await sec()===s0&&await ev(()=>__N5.AL().cur===3&&!__N5.AL().log[__N5.todayStr()]));
 ok('undo clears goal-met flag when below goal',await ev(()=>!__N5.goalMet()));
 await tap('#alOpen');await tap('#alDone');
 await p.reload();await p.waitForTimeout(800);ok('persists after reload',await ev(()=>__N5.AL().cur===4)&&/done/.test(await p.textContent('#alCard')));
 await tap('#tabStats');ok('Stats history shows audio lessons',/1/.test(await p.textContent('#hAud'))&&/25m/.test(await p.textContent('#hAud')));
 ok('history bar notes the lesson',await ev(()=>[...document.querySelectorAll('.bar')].some(b=>/lesson 3/.test(b.title))));
 await p.emulateMedia({colorScheme:'dark'});await tap('#tabHome');if(SHOT)await p.screenshot({path:SHOT+'al-done-dark.png'});
 await tap('#tabSettings');await tap('#alOn');await tap('#tabHome');ok('toggle off hides the step',!(await p.$('#alCard')));
 ok('vocab progress intact',await ev(()=>Object.keys(__N5.S().cards).length===300));
 ok('no page errors',errs.length===0,JSON.stringify(errs.slice(0,3)));
 console.log('SUMMARY',BR,R.filter(x=>x).length,'/',R.length);await b.close();
})().catch(e=>{console.log('CRASH',e.message.slice(0,500));process.exit(1)});
